// Backup of current database data before schema update
export const backupData = {
  departments: [
    { id: 'cmfwr6qy20000mv56yi2ho6g5', name: 'Lamination' },
    { id: 'cmfwr6r0l0001mv56tlj11fu5', name: 'Shipping' },
    { id: 'cmfwr6r1q0002mv56bur5x5hl', name: 'QA' },
    { id: 'cmfwr6r570003mv56otaw9zhy', name: 'Kitting' },
    { id: 'cmfwr6r570004mv56mouqlg1d', name: 'Final Rigging' },
    { id: 'cmfwr6r5k0005mv56leylwu4o', name: 'Capping' },
    { id: 'cmfwr6r5r0007mv56rezc2jv9', name: 'Water Test' },
    { id: 'cmfwr6r5r0006mv56jsa5wy6q', name: 'Engine Hang' },
    { id: 'cmfwr6r5y0008mv56um3jo3ez', name: 'Deck Rigging' },
    { id: 'cmfwr6r660009mv56j89zqwqk', name: 'Hull Rigging' },
    { id: 'cmfwr6r6j000amv56md5pbmfe', name: 'Cleaning' },
  ],
  users: [
    {
      id: 'cmfwr6s9e001jmv5659vvhrqm',
      email: 'admin@cri.local',
      passwordHash: '$2b$12$4cvQAnsDxPW8eZ.DLoF.he/tKys3jzCjz4rIwhEznEFA/YdH2mxLa',
      role: 'ADMIN',
      departmentId: null,
      hourlyRate: 45.0,
      shiftSchedule: {
        days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
        startTime: '08:00',
        endTime: '17:00',
      },
    },
    {
      id: 'cmfwr6s9e001kmv5660mr74fo',
      email: 'supervisor@cri.local',
      passwordHash: '$2b$12$Om0qEF9ScNotcaDnoqY4h.FTfxf5TkPOiM.nMPEFKOYLosf.Q0V2e',
      role: 'SUPERVISOR',
      departmentId: 'cmfwr6r660009mv56j89zqwqk',
      hourlyRate: 35.0,
      shiftSchedule: {
        days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
        startTime: '07:00',
        endTime: '16:00',
      },
    },
    {
      id: 'cmfwr6s9e001lmv567pcikcpy',
      email: 'operator@cri.local',
      passwordHash: '$2b$12$NL98avVAWBajkgLuavY2AOnHplC.ws6tUaYaU/noj09coe5fbOOR6',
      role: 'OPERATOR',
      departmentId: 'cmfwr6r660009mv56j89zqwqk',
      hourlyRate: 22.5,
      shiftSchedule: {
        days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
        startTime: '08:00',
        endTime: '17:00',
      },
    },
    {
      id: 'cmfwr6s9e001mmv56newuser01',
      email: 'joe.smith@cri.local',
      passwordHash: '$2b$12$NL98avVAWBajkgLuavY2AOnHplC.ws6tUaYaU/noj09coe5fbOOR6',
      role: 'OPERATOR',
      departmentId: 'cmfwr6qy20000mv56yi2ho6g5',
      hourlyRate: 20.0,
      shiftSchedule: {
        days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
        startTime: '08:00',
        endTime: '17:00',
      },
    },
    {
      id: 'cmfwr6s9e001nmv56newuser02',
      email: 'dave.jones@cri.local',
      passwordHash: '$2b$12$NL98avVAWBajkgLuavY2AOnHplC.ws6tUaYaU/noj09coe5fbOOR6',
      role: 'OPERATOR',
      departmentId: 'cmfwr6r5y0008mv56um3jo3ez',
      hourlyRate: 25.0,
      shiftSchedule: {
        days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
        startTime: '06:00',
        endTime: '15:00',
      },
    },
  ],
  workCenters: [
    {
      id: 'cmfwr6r95000rmv56pz1n5v4x',
      name: 'Hull Rigging',
      departmentId: 'cmfwr6r660009mv56j89zqwqk',
      isActive: true,
    },
    {
      id: 'cmfwr6r95000smv562kq5d6ur',
      name: 'Shipping',
      departmentId: 'cmfwr6r0l0001mv56tlj11fu5',
      isActive: true,
    },
    {
      id: 'cmfwr6r95000omv56qcz8jid7',
      name: 'QA',
      departmentId: 'cmfwr6r1q0002mv56bur5x5hl',
      isActive: true,
    },
    {
      id: 'cmfwr6r94000kmv56iidjxbj4',
      name: 'Engine Hang',
      departmentId: 'cmfwr6r5r0006mv56jsa5wy6q',
      isActive: true,
    },
    {
      id: 'cmfwr6r94000emv56qvlppsw9',
      name: 'Kitting',
      departmentId: 'cmfwr6r570003mv56otaw9zhy',
      isActive: true,
    },
    {
      id: 'cmfwr6r94000cmv56sa1ryiql',
      name: 'Lamination',
      departmentId: 'cmfwr6qy20000mv56yi2ho6g5',
      isActive: true,
    },
    {
      id: 'cmfwr6r94000hmv56qwegzllh',
      name: 'Deck Rigging',
      departmentId: 'cmfwr6r5y0008mv56um3jo3ez',
      isActive: true,
    },
    {
      id: 'cmfwr6r94000mmv56mpq7cdnh',
      name: 'Final Rigging',
      departmentId: 'cmfwr6r570004mv56mouqlg1d',
      isActive: true,
    },
    {
      id: 'cmfwr6r94000imv56khmieqcr',
      name: 'Capping',
      departmentId: 'cmfwr6r5k0005mv56leylwu4o',
      isActive: true,
    },
    {
      id: 'cmfwr6rbh000umv561qu7ur41',
      name: 'Cleaning',
      departmentId: 'cmfwr6r6j000amv56md5pbmfe',
      isActive: true,
    },
    {
      id: 'cmfwr6rbi000wmv567v5jr36o',
      name: 'Water Test',
      departmentId: 'cmfwr6r5r0007mv56rezc2jv9',
      isActive: true,
    },
  ],
  stations: [
    {
      id: 'cmfwr6rco000ymv56m8bynk1b',
      code: 'DRIG-1',
      name: 'Deck Rigging Station 1',
      description: 'Primary deck rigging workstation',
      workCenterId: 'cmfwr6r94000hmv56qwegzllh',
      defaultPayRate: 24.0,
      capacity: 2,
      targetCycleTimeSeconds: 9000,
      isActive: true,
    },
    {
      id: 'cmfwr6rco0011mv56n62uc0sj',
      code: 'LAM-1',
      name: 'Lamination Station 1',
      description: 'Main lamination work area',
      workCenterId: 'cmfwr6r94000cmv56sa1ryiql',
      defaultPayRate: 22.0,
      capacity: 3,
      targetCycleTimeSeconds: 14400,
      isActive: true,
    },
    {
      id: 'cmfwr6rcp001emv569rfhss65',
      code: 'ENG-1',
      name: 'Engine Hang Station 1',
      description: 'Engine installation and rigging',
      workCenterId: 'cmfwr6r94000kmv56iidjxbj4',
      defaultPayRate: 28.0,
      capacity: 2,
      targetCycleTimeSeconds: 7200,
      isActive: true,
    },
    {
      id: 'cmfwr6rcp0018mv56qark6z6q',
      code: 'HRIG-1',
      name: 'Hull Rigging Station 1',
      description: 'Hull assembly and rigging',
      workCenterId: 'cmfwr6r95000rmv56pz1n5v4x',
      defaultPayRate: 23.0,
      capacity: 2,
      targetCycleTimeSeconds: 10800,
      isActive: true,
    },
    {
      id: 'cmfwr6rco0014mv56nhkbfzxf',
      code: 'FRIG-1',
      name: 'Final Rigging Station 1',
      description: 'Final rigging and assembly',
      workCenterId: 'cmfwr6r94000mmv56mpq7cdnh',
      defaultPayRate: 26.0,
      capacity: 2,
      targetCycleTimeSeconds: 10800,
      isActive: true,
    },
    {
      id: 'cmfwr6rcp001amv56scc3phfl',
      code: 'CAP-1',
      name: 'Capping Station 1',
      description: 'Capping and sealing operations',
      workCenterId: 'cmfwr6r94000imv56khmieqcr',
      defaultPayRate: 21.0,
      capacity: 2,
      targetCycleTimeSeconds: 5400,
      isActive: true,
    },
    {
      id: 'cmfwr6rcp001cmv56ybyjly1h',
      code: 'CLEAN-1',
      name: 'Cleaning Station 1',
      description: 'Final cleaning and detailing',
      workCenterId: 'cmfwr6rbh000umv561qu7ur41',
      defaultPayRate: 18.0,
      capacity: 2,
      targetCycleTimeSeconds: 3600,
      isActive: true,
    },
    {
      id: 'cmfwr6rcp0016mv56la2yxlr6',
      code: 'WTEST-1',
      name: 'Water Test Station 1',
      description: 'Water testing and leak detection',
      workCenterId: 'cmfwr6rbi000wmv567v5jr36o',
      defaultPayRate: 24.0,
      capacity: 1,
      targetCycleTimeSeconds: 3600,
      isActive: true,
    },
    {
      id: 'cmfwr6rco0012mv5674ynuavm',
      code: 'QA-1',
      name: 'QA Station 1',
      description: 'Quality assurance and inspection',
      workCenterId: 'cmfwr6r95000omv56qcz8jid7',
      defaultPayRate: 27.0,
      capacity: 1,
      targetCycleTimeSeconds: 5400,
      isActive: true,
    },
    {
      id: 'cmfwr6rez001gmv56h7f2kn9n',
      code: 'KIT-1',
      name: 'Kitting Station 1',
      description: 'Parts kitting and preparation',
      workCenterId: 'cmfwr6r94000emv56qvlppsw9',
      defaultPayRate: 19.0,
      capacity: 3,
      targetCycleTimeSeconds: 7200,
      isActive: true,
    },
    {
      id: 'cmfwr6rez001imv56al1dursc',
      code: 'SHIP-1',
      name: 'Shipping Station 1',
      description: 'Final packaging and shipping prep',
      workCenterId: 'cmfwr6r95000smv562kq5d6ur',
      defaultPayRate: 20.0,
      capacity: 2,
      targetCycleTimeSeconds: 1800,
      isActive: true,
    },
  ],
  routingVersions: [
    {
      id: 'cmfwr6se2001mmv56lv18hemd',
      model: 'LX24',
      trim: 'Base',
      featuresJson: {},
      version: 1,
      status: 'RELEASED',
      releasedAt: '2025-09-23T16:12:09.145Z',
    },
  ],
  routingStages: [
    {
      id: 'cmfwr6sgg001qmv56n8psxy66',
      routingVersionId: 'cmfwr6se2001mmv56lv18hemd',
      sequence: 2,
      code: 'LAMINATION',
      name: 'Lamination',
      enabled: true,
      workCenterId: 'cmfwr6r94000cmv56sa1ryiql',
      standardStageSeconds: 14400,
    },
    {
      id: 'cmfwr6sgg001omv56y3572k6m',
      routingVersionId: 'cmfwr6se2001mmv56lv18hemd',
      sequence: 1,
      code: 'KITTING',
      name: 'Kitting',
      enabled: true,
      workCenterId: 'cmfwr6r94000emv56qvlppsw9',
      standardStageSeconds: 7200,
    },
    {
      id: 'cmfwr6sgi001umv56pnt4ssaa',
      routingVersionId: 'cmfwr6se2001mmv56lv18hemd',
      sequence: 4,
      code: 'DECK_RIGGING',
      name: 'Deck Rigging',
      enabled: true,
      workCenterId: 'cmfwr6r94000hmv56qwegzllh',
      standardStageSeconds: 9000,
    },
    {
      id: 'cmfwr6sgi001wmv56ob211vku',
      routingVersionId: 'cmfwr6se2001mmv56lv18hemd',
      sequence: 5,
      code: 'CAPPING',
      name: 'Capping',
      enabled: true,
      workCenterId: 'cmfwr6r94000imv56khmieqcr',
      standardStageSeconds: 5400,
    },
    {
      id: 'cmfwr6sgh001smv56rhcwys96',
      routingVersionId: 'cmfwr6se2001mmv56lv18hemd',
      sequence: 3,
      code: 'HULL_RIGGING',
      name: 'Hull Rigging',
      enabled: true,
      workCenterId: 'cmfwr6r95000rmv56pz1n5v4x',
      standardStageSeconds: 10800,
    },
    {
      id: 'cmfwr6sgk0022mv56iijtru0f',
      routingVersionId: 'cmfwr6se2001mmv56lv18hemd',
      sequence: 8,
      code: 'WATER_TEST',
      name: 'Water Test',
      enabled: true,
      workCenterId: 'cmfwr6rbi000wmv567v5jr36o',
      standardStageSeconds: 3600,
    },
    {
      id: 'cmfwr6sgl0024mv56lkon4ip8',
      routingVersionId: 'cmfwr6se2001mmv56lv18hemd',
      sequence: 9,
      code: 'QA',
      name: 'QA',
      enabled: true,
      workCenterId: 'cmfwr6r95000omv56qcz8jid7',
      standardStageSeconds: 5400,
    },
    {
      id: 'cmfwr6sgj001ymv56own56sr9',
      routingVersionId: 'cmfwr6se2001mmv56lv18hemd',
      sequence: 6,
      code: 'ENGINE_HANG',
      name: 'Engine Hang',
      enabled: true,
      workCenterId: 'cmfwr6r94000kmv56iidjxbj4',
      standardStageSeconds: 7200,
    },
    {
      id: 'cmfwr6sgk0020mv56s1jm6vhm',
      routingVersionId: 'cmfwr6se2001mmv56lv18hemd',
      sequence: 7,
      code: 'FINAL_RIGGING',
      name: 'Final Rigging',
      enabled: true,
      workCenterId: 'cmfwr6r94000mmv56mpq7cdnh',
      standardStageSeconds: 10800,
    },
    {
      id: 'cmfwr6siq0026mv56ek2ugef6',
      routingVersionId: 'cmfwr6se2001mmv56lv18hemd',
      sequence: 10,
      code: 'CLEANING',
      name: 'Cleaning',
      enabled: true,
      workCenterId: 'cmfwr6rbh000umv561qu7ur41',
      standardStageSeconds: 3600,
    },
    {
      id: 'cmfwr6sir0028mv56oiz8kaa1',
      routingVersionId: 'cmfwr6se2001mmv56lv18hemd',
      sequence: 11,
      code: 'SHIPPING',
      name: 'Shipping',
      enabled: true,
      workCenterId: 'cmfwr6r95000smv562kq5d6ur',
      standardStageSeconds: 1800,
    },
  ],
  workOrders: [
    {
      id: 'cmfwr6sjx002amv565vdp8f8e',
      number: 'WO-1001',
      hullId: 'HULL-TEST-001',
      productSku: 'LX24-BASE',
      specSnapshot: {
        trim: 'Base',
        model: 'LX24',
        stages: [
          { code: 'KITTING', name: 'Kitting', sequence: 1 },
          { code: 'LAMINATION', name: 'Lamination', sequence: 2 },
          { code: 'HULL_RIGGING', name: 'Hull Rigging', sequence: 3 },
          { code: 'DECK_RIGGING', name: 'Deck Rigging', sequence: 4 },
          { code: 'CAPPING', name: 'Capping', sequence: 5 },
          { code: 'ENGINE_HANG', name: 'Engine Hang', sequence: 6 },
          { code: 'FINAL_RIGGING', name: 'Final Rigging', sequence: 7 },
          { code: 'WATER_TEST', name: 'Water Test', sequence: 8 },
          { code: 'QA', name: 'QA', sequence: 9 },
          { code: 'CLEANING', name: 'Cleaning', sequence: 10 },
          { code: 'SHIPPING', name: 'Shipping', sequence: 11 },
        ],
        features: {},
        routingVersionId: 'cmfwr6se2001mmv56lv18hemd',
      },
      qty: 1,
      status: 'IN_PROGRESS',
      routingVersionId: 'cmfwr6se2001mmv56lv18hemd',
      currentStageIndex: 1,
      createdAt: '2025-09-23T16:12:09.357Z',
    },
  ],
  woStageLogs: [
    {
      id: 'cmfy58z7m0001mm8pu1ia1crc',
      workOrderId: 'cmfwr6sjx002amv565vdp8f8e',
      routingStageId: 'cmfwr6sgg001omv56y3572k6m',
      stationId: 'cmfwr6rez001gmv56h7f2kn9n',
      userId: 'cmfwr6s9e001lmv567pcikcpy',
      event: 'START',
      goodQty: 0,
      scrapQty: 0,
      note: null,
      createdAt: '2025-09-24T15:33:32.098Z',
    },
    {
      id: 'cmfy59oq60003mm8p2wtr0vac',
      workOrderId: 'cmfwr6sjx002amv565vdp8f8e',
      routingStageId: 'cmfwr6sgg001omv56y3572k6m',
      stationId: 'cmfwr6rez001gmv56h7f2kn9n',
      userId: 'cmfwr6s9e001lmv567pcikcpy',
      event: 'COMPLETE',
      goodQty: 1,
      scrapQty: 0,
      note: 'Kits are ready to go.',
      createdAt: '2025-09-24T15:34:05.166Z',
    },
    {
      id: 'cmfy5avk10005mm8p0ffv1qi8',
      workOrderId: 'cmfwr6sjx002amv565vdp8f8e',
      routingStageId: 'cmfwr6sgg001qmv56n8psxy66',
      stationId: 'cmfwr6rco0011mv56n62uc0sj',
      userId: 'cmfwr6s9e001lmv567pcikcpy',
      event: 'START',
      goodQty: 0,
      scrapQty: 0,
      note: null,
      createdAt: '2025-09-24T15:35:00.673Z',
    },
  ],
  productModels: [
    {
      id: 'cmg6o0tot0000vwgdgtbkfgkw',
      name: 'LX24',
      description: '24-foot luxury boat model',
      isActive: true,
      createdAt: '2025-09-30T14:41:13.805Z',
    },
    {
      id: 'cmg6o0tot0001vwgdytuxaj48',
      name: 'LX26',
      description: '26-foot luxury boat model',
      isActive: true,
      createdAt: '2025-09-30T14:41:13.805Z',
    },
    {
      id: 'cfg-model-lx22',
      name: 'LX22',
      description: '22-foot crossover model',
      isActive: true,
      createdAt: '2025-10-30T12:00:00.000Z',
    },
    {
      id: 'cfg-model-lx21',
      name: 'LX21',
      description: '21-foot fishing edition',
      isActive: true,
      createdAt: '2025-10-30T12:00:00.000Z',
    },
  ],
  productTrims: [
    {
      id: 'cmg6o0tou0002vwgd8ht7mklp',
      productModelId: 'cmg6o0tot0000vwgdgtbkfgkw',
      name: 'Base',
      description: 'Entry-level trim with essential features',
      isActive: true,
      createdAt: '2025-09-30T14:41:13.810Z',
    },
    {
      id: 'cmg6o0tou0003vwgdp9x4nqrs',
      productModelId: 'cmg6o0tot0000vwgdgtbkfgkw',
      name: 'Sport',
      description: 'Performance-oriented trim with enhanced features',
      isActive: true,
      createdAt: '2025-09-30T14:41:13.811Z',
    },
    {
      id: 'cmg6o0tou0004vwgdt2y5wvnm',
      productModelId: 'cmg6o0tot0000vwgdgtbkfgkw',
      name: 'Luxury',
      description: 'Premium trim with luxury amenities and finishes',
      isActive: true,
      createdAt: '2025-09-30T14:41:13.812Z',
    },
    {
      id: 'cmg6o0tou0005vwgdx7k9plqw',
      productModelId: 'cmg6o0tot0001vwgdytuxaj48',
      name: 'Base',
      description: 'Entry-level trim with essential features',
      isActive: true,
      createdAt: '2025-09-30T14:41:13.813Z',
    },
    {
      id: 'cmg6o0tou0006vwgdm4r8szbn',
      productModelId: 'cmg6o0tot0001vwgdytuxaj48',
      name: 'Sport',
      description: 'Performance-oriented trim with enhanced features',
      isActive: true,
      createdAt: '2025-09-30T14:41:13.814Z',
    },
    {
      id: 'cmg6o0tou0007vwgdq9t3hxyz',
      productModelId: 'cmg6o0tot0001vwgdytuxaj48',
      name: 'Luxury',
      description: 'Premium trim with luxury amenities and finishes',
      isActive: true,
      createdAt: '2025-09-30T14:41:13.815Z',
    },
    {
      id: 'cmg6o0tou0008vwgdv6p2mjkl',
      productModelId: 'cmg6o0tot0001vwgdytuxaj48',
      name: 'Premium',
      description: 'Top-tier trim with all available features and upgrades',
      isActive: true,
      createdAt: '2025-09-30T14:41:13.816Z',
    },
    {
      id: 'cfg-trim-lx22-base',
      productModelId: 'cfg-model-lx22',
      name: 'Base',
      description: 'Standard LX22 configuration',
      isActive: true,
      createdAt: '2025-10-30T12:00:00.000Z',
    },
    {
      id: 'cfg-trim-lx22-sport',
      productModelId: 'cfg-model-lx22',
      name: 'Sport',
      description: 'Performance package with tower and ballast',
      isActive: true,
      createdAt: '2025-10-30T12:00:00.000Z',
    },
    {
      id: 'cfg-trim-lx22-luxury',
      productModelId: 'cfg-model-lx22',
      name: 'Luxury',
      description: 'Luxury interior and lighting upgrades',
      isActive: true,
      createdAt: '2025-10-30T12:00:00.000Z',
    },
    {
      id: 'cfg-trim-lx21-base',
      productModelId: 'cfg-model-lx21',
      name: 'Base',
      description: 'Entry LX21 angler package',
      isActive: true,
      createdAt: '2025-10-30T12:00:00.000Z',
    },
    {
      id: 'cfg-trim-lx21-angler',
      productModelId: 'cfg-model-lx21',
      name: 'Angler Pro',
      description: 'Tournament-ready angler upgrades',
      isActive: true,
      createdAt: '2025-10-30T12:00:00.000Z',
    },
  ],
  productConfigurationSections: [
    {
      id: 'cfg-sec-lx26-electrical',
      productModelId: 'cmg6o0tot0001vwgdytuxaj48',
      productTrimId: null,
      code: 'ELECTRICAL',
      name: 'Electrical Systems',
      description:
        'Power management, charging, and entertainment subsystems for LX26 fleet builds.',
      sortOrder: 1,
      isRequired: true,
      createdAt: '2025-10-30T12:05:00.000Z',
    },
    {
      id: 'cfg-sec-lx26-performance',
      productModelId: 'cmg6o0tot0001vwgdytuxaj48',
      productTrimId: null,
      code: 'PERFORMANCE',
      name: 'Performance Packages',
      description: 'Propulsion and tow sport upgrades that impact LX26 driveline setup.',
      sortOrder: 2,
      isRequired: true,
      createdAt: '2025-10-30T12:05:00.000Z',
    },
    {
      id: 'cfg-sec-lx26-luxury',
      productModelId: 'cmg6o0tot0001vwgdytuxaj48',
      productTrimId: 'cmg6o0tou0007vwgdq9t3hxyz',
      code: 'LUXURY_COMFORT',
      name: 'Luxury Comfort',
      description:
        'Premium upholstery and ambient lighting selections exclusive to LX26 Luxury trim.',
      sortOrder: 1,
      isRequired: true,
      createdAt: '2025-10-30T12:05:00.000Z',
    },
    {
      id: 'cfg-sec-lx24-powertrain',
      productModelId: 'cmg6o0tot0000vwgdgtbkfgkw',
      productTrimId: null,
      code: 'POWERTRAIN',
      name: 'Powertrain',
      description: 'Engine and helm configuration for LX24 production.',
      sortOrder: 1,
      isRequired: true,
      createdAt: '2025-10-30T12:05:00.000Z',
    },
    {
      id: 'cfg-sec-lx24-audio',
      productModelId: 'cmg6o0tot0000vwgdgtbkfgkw',
      productTrimId: null,
      code: 'AUDIO',
      name: 'Audio & Entertainment',
      description: 'Speaker arrays, subwoofers, and cabin media upgrades for LX24.',
      sortOrder: 2,
      isRequired: false,
      createdAt: '2025-10-30T12:05:00.000Z',
    },
    {
      id: 'cfg-sec-lx22-adventure',
      productModelId: 'cfg-model-lx22',
      productTrimId: null,
      code: 'ADVENTURE',
      name: 'Adventure Essentials',
      description: 'Fuel capacity and shading selections for LX22 lake-ready bundles.',
      sortOrder: 1,
      isRequired: true,
      createdAt: '2025-10-30T12:05:00.000Z',
    },
    {
      id: 'cfg-sec-lx22-luxury',
      productModelId: 'cfg-model-lx22',
      productTrimId: 'cfg-trim-lx22-luxury',
      code: 'LUXURY',
      name: 'LX22 Luxury Upgrades',
      description: 'Interior and galley options bundled with the LX22 Luxury trim.',
      sortOrder: 1,
      isRequired: true,
      createdAt: '2025-10-30T12:05:00.000Z',
    },
    {
      id: 'cfg-sec-lx21-fishing',
      productModelId: 'cfg-model-lx21',
      productTrimId: null,
      code: 'FISHING',
      name: 'Fishing Layout',
      description: 'Livewell and tackle storage configuration for LX21 hulls.',
      sortOrder: 1,
      isRequired: true,
      createdAt: '2025-10-30T12:05:00.000Z',
    },
    {
      id: 'cfg-sec-lx21-electronics',
      productModelId: 'cfg-model-lx21',
      productTrimId: 'cfg-trim-lx21-angler',
      code: 'ELECTRONICS',
      name: 'Electronics & Control',
      description: 'Fishfinder and trolling motor pairings for Angler Pro builds.',
      sortOrder: 1,
      isRequired: true,
      createdAt: '2025-10-30T12:05:00.000Z',
    },
  ],
  productConfigurationComponents: [
    {
      id: 'cfg-comp-lx26-battery',
      sectionId: 'cfg-sec-lx26-electrical',
      code: 'BATTERY_PACKAGE',
      name: 'Battery Package',
      description: 'Dual battery selections sized for LX26 accessories and power demands.',
      isRequired: true,
      allowMultiple: false,
      defaultOptionId: 'cfg-opt-lx26-battery-standard',
      sortOrder: 1,
      createdAt: '2025-10-30T12:06:00.000Z',
    },
    {
      id: 'cfg-comp-lx26-charger',
      sectionId: 'cfg-sec-lx26-electrical',
      code: 'CHARGER',
      name: 'Onboard Charger',
      description: 'Factory-installed charging solution sized for selected batteries.',
      isRequired: true,
      allowMultiple: false,
      defaultOptionId: 'cfg-opt-lx26-charger-30a',
      sortOrder: 2,
      createdAt: '2025-10-30T12:06:00.000Z',
    },
    {
      id: 'cfg-comp-lx26-stereo',
      sectionId: 'cfg-sec-lx26-electrical',
      code: 'STEREO',
      name: 'Stereo Package',
      description: 'Cabin and tower stereo configurations.',
      isRequired: false,
      allowMultiple: false,
      defaultOptionId: 'cfg-opt-lx26-stereo-premium',
      sortOrder: 3,
      createdAt: '2025-10-30T12:06:00.000Z',
    },
    {
      id: 'cfg-comp-lx26-propeller',
      sectionId: 'cfg-sec-lx26-performance',
      code: 'PROPELLER',
      name: 'Propeller',
      description: 'Stainless propeller pitched for hull loading and engine selection.',
      isRequired: true,
      allowMultiple: false,
      defaultOptionId: 'cfg-opt-lx26-prop-19p',
      sortOrder: 1,
      createdAt: '2025-10-30T12:06:00.000Z',
    },
    {
      id: 'cfg-comp-lx26-tow',
      sectionId: 'cfg-sec-lx26-performance',
      code: 'TOW_PACKAGE',
      name: 'Tow Sports Package',
      description: 'Tower and ballast options for watersports customers.',
      isRequired: false,
      allowMultiple: false,
      defaultOptionId: 'cfg-opt-lx26-tow-standard',
      sortOrder: 2,
      createdAt: '2025-10-30T12:06:00.000Z',
    },
    {
      id: 'cfg-comp-lx26-lux-seating',
      sectionId: 'cfg-sec-lx26-luxury',
      code: 'SEATING_UPHOLSTERY',
      name: 'Seating Upholstery',
      description: 'Premium seating materials for luxury LX26 cabins.',
      isRequired: true,
      allowMultiple: false,
      defaultOptionId: 'cfg-opt-lx26-lux-seating-diamond',
      sortOrder: 1,
      createdAt: '2025-10-30T12:06:00.000Z',
    },
    {
      id: 'cfg-comp-lx26-lux-lighting',
      sectionId: 'cfg-sec-lx26-luxury',
      code: 'LIGHTING',
      name: 'Ambient Lighting',
      description: 'Cockpit and underwater lighting systems.',
      isRequired: true,
      allowMultiple: false,
      defaultOptionId: 'cfg-opt-lx26-lux-lighting-rgb',
      sortOrder: 2,
      createdAt: '2025-10-30T12:06:00.000Z',
    },
    {
      id: 'cfg-comp-lx24-engine',
      sectionId: 'cfg-sec-lx24-powertrain',
      code: 'ENGINE_SELECTION',
      name: 'Engine Selection',
      description: 'Outboard engine options for LX24.',
      isRequired: true,
      allowMultiple: false,
      defaultOptionId: 'cfg-opt-lx24-engine-300',
      sortOrder: 1,
      createdAt: '2025-10-30T12:06:00.000Z',
    },
    {
      id: 'cfg-comp-lx24-helm',
      sectionId: 'cfg-sec-lx24-powertrain',
      code: 'HELM_LAYOUT',
      name: 'Helm Layout',
      description: 'Console controls and dash layout.',
      isRequired: true,
      allowMultiple: false,
      defaultOptionId: 'cfg-opt-lx24-helm-dual',
      sortOrder: 2,
      createdAt: '2025-10-30T12:06:00.000Z',
    },
    {
      id: 'cfg-comp-lx24-speakers',
      sectionId: 'cfg-sec-lx24-audio',
      code: 'SPEAKER_PACKAGE',
      name: 'Speaker Package',
      description: 'Cabin speaker array selection.',
      isRequired: true,
      allowMultiple: false,
      defaultOptionId: 'cfg-opt-lx24-speaker-standard',
      sortOrder: 1,
      createdAt: '2025-10-30T12:06:00.000Z',
    },
    {
      id: 'cfg-comp-lx24-subwoofer',
      sectionId: 'cfg-sec-lx24-audio',
      code: 'SUBWOOFER',
      name: 'Subwoofer',
      description: 'Optional subwoofer placement.',
      isRequired: false,
      allowMultiple: false,
      defaultOptionId: 'cfg-opt-lx24-subwoofer-none',
      sortOrder: 2,
      createdAt: '2025-10-30T12:06:00.000Z',
    },
    {
      id: 'cfg-comp-lx22-fuel',
      sectionId: 'cfg-sec-lx22-adventure',
      code: 'FUEL_TANK',
      name: 'Fuel Tank',
      description: 'Fuel capacity selections for LX22 trips.',
      isRequired: true,
      allowMultiple: false,
      defaultOptionId: 'cfg-opt-lx22-fuel-50gal',
      sortOrder: 1,
      createdAt: '2025-10-30T12:06:00.000Z',
    },
    {
      id: 'cfg-comp-lx22-bimini',
      sectionId: 'cfg-sec-lx22-adventure',
      code: 'BIMINI',
      name: 'Bimini Top',
      description: 'Shade options for LX22 customers.',
      isRequired: false,
      allowMultiple: false,
      defaultOptionId: 'cfg-opt-lx22-bimini-sun',
      sortOrder: 2,
      createdAt: '2025-10-30T12:06:00.000Z',
    },
    {
      id: 'cfg-comp-lx22-lux-seating',
      sectionId: 'cfg-sec-lx22-luxury',
      code: 'SEATING',
      name: 'Seating Surfaces',
      description: 'Luxury upholstery kits for LX22.',
      isRequired: true,
      allowMultiple: false,
      defaultOptionId: 'cfg-opt-lx22-lux-seating-perf',
      sortOrder: 1,
      createdAt: '2025-10-30T12:06:00.000Z',
    },
    {
      id: 'cfg-comp-lx22-lux-galley',
      sectionId: 'cfg-sec-lx22-luxury',
      code: 'GALLEY',
      name: 'Galley Module',
      description: 'Galley and refreshment station packages.',
      isRequired: true,
      allowMultiple: false,
      defaultOptionId: 'cfg-opt-lx22-lux-galley-deluxe',
      sortOrder: 2,
      createdAt: '2025-10-30T12:06:00.000Z',
    },
    {
      id: 'cfg-comp-lx21-livewell',
      sectionId: 'cfg-sec-lx21-fishing',
      code: 'LIVEWELL',
      name: 'Livewell System',
      description: 'Recirculating livewell packages for LX21.',
      isRequired: true,
      allowMultiple: false,
      defaultOptionId: 'cfg-opt-lx21-livewell-dual',
      sortOrder: 1,
      createdAt: '2025-10-30T12:06:00.000Z',
    },
    {
      id: 'cfg-comp-lx21-rod',
      sectionId: 'cfg-sec-lx21-fishing',
      code: 'ROD_STORAGE',
      name: 'Rod Storage',
      description: 'Locker and deck rod storage configurations.',
      isRequired: true,
      allowMultiple: false,
      defaultOptionId: 'cfg-opt-lx21-rod-locker',
      sortOrder: 2,
      createdAt: '2025-10-30T12:06:00.000Z',
    },
    {
      id: 'cfg-comp-lx21-electronics',
      sectionId: 'cfg-sec-lx21-electronics',
      code: 'ELECTRONICS',
      name: 'Electronics Suite',
      description: 'Fishfinder and display selections for Angler Pro.',
      isRequired: true,
      allowMultiple: false,
      defaultOptionId: 'cfg-opt-lx21-electronics-hds',
      sortOrder: 1,
      createdAt: '2025-10-30T12:06:00.000Z',
    },
    {
      id: 'cfg-comp-lx21-trolling',
      sectionId: 'cfg-sec-lx21-electronics',
      code: 'TROLLING_MOTOR',
      name: 'Trolling Motor',
      description: 'Bow mount trolling motor packages.',
      isRequired: true,
      allowMultiple: false,
      defaultOptionId: 'cfg-opt-lx21-trolling-112',
      sortOrder: 2,
      createdAt: '2025-10-30T12:06:00.000Z',
    },
  ],
  productConfigurationOptions: [
    {
      id: 'cfg-opt-lx26-battery-standard',
      componentId: 'cfg-comp-lx26-battery',
      code: 'BAT-STD',
      partNumber: 'LX26-BAT-STD',
      name: 'Dual AGM 31 Series',
      description: 'Standard dual AGM batteries for LX26.',
      isActive: true,
      isDefault: true,
      sortOrder: 1,
      createdAt: '2025-10-30T12:07:00.000Z',
    },
    {
      id: 'cfg-opt-lx26-battery-heavy',
      componentId: 'cfg-comp-lx26-battery',
      code: 'BAT-HVY',
      partNumber: 'LX26-BAT-HVY',
      name: 'Triple Lithium Upgrade',
      description: 'High-capacity lithium battery bank for accessory-heavy builds.',
      isActive: true,
      isDefault: false,
      sortOrder: 2,
      createdAt: '2025-10-30T12:07:00.000Z',
    },
    {
      id: 'cfg-opt-lx26-charger-30a',
      componentId: 'cfg-comp-lx26-charger',
      code: 'CHR-30A',
      partNumber: 'LX26-CHR-30A',
      name: '30A Smart Charger',
      description: 'Standard three-bank smart charger.',
      isActive: true,
      isDefault: true,
      sortOrder: 1,
      createdAt: '2025-10-30T12:07:00.000Z',
    },
    {
      id: 'cfg-opt-lx26-charger-50a',
      componentId: 'cfg-comp-lx26-charger',
      code: 'CHR-50A',
      partNumber: 'LX26-CHR-50A',
      name: '50A High Output Charger',
      description: 'Upgraded charger matched to lithium battery upgrade.',
      isActive: true,
      isDefault: false,
      sortOrder: 2,
      createdAt: '2025-10-30T12:07:00.000Z',
    },
    {
      id: 'cfg-opt-lx26-stereo-premium',
      componentId: 'cfg-comp-lx26-stereo',
      code: 'AUD-PREMIUM',
      partNumber: 'LX26-AUD-PREM',
      name: 'Premium 8 Speaker',
      description: 'Premier stereo with cabin and tower zone control.',
      isActive: true,
      isDefault: true,
      sortOrder: 1,
      createdAt: '2025-10-30T12:07:00.000Z',
    },
    {
      id: 'cfg-opt-lx26-stereo-concert',
      componentId: 'cfg-comp-lx26-stereo',
      code: 'AUD-CONCERT',
      partNumber: 'LX26-AUD-CON',
      name: 'Concert Series',
      description: 'Concert-level system with DSP and tower cans.',
      isActive: true,
      isDefault: false,
      sortOrder: 2,
      createdAt: '2025-10-30T12:07:00.000Z',
    },
    {
      id: 'cfg-opt-lx26-prop-19p',
      componentId: 'cfg-comp-lx26-propeller',
      code: 'PROP-19P',
      partNumber: 'LX26-PROP-19',
      name: '19P Stainless',
      description: 'Balanced performance for general duty.',
      isActive: true,
      isDefault: true,
      sortOrder: 1,
      createdAt: '2025-10-30T12:07:00.000Z',
    },
    {
      id: 'cfg-opt-lx26-prop-21p',
      componentId: 'cfg-comp-lx26-propeller',
      code: 'PROP-21P',
      partNumber: 'LX26-PROP-21',
      name: '21P Stainless',
      description: 'Performance prop for high altitude or heavy loads.',
      isActive: true,
      isDefault: false,
      sortOrder: 2,
      createdAt: '2025-10-30T12:07:00.000Z',
    },
    {
      id: 'cfg-opt-lx26-tow-standard',
      componentId: 'cfg-comp-lx26-tow',
      code: 'TOW-STD',
      partNumber: 'LX26-TOW-STD',
      name: 'Standard Tow Package',
      description: 'Ski pylon and ballast bags.',
      isActive: true,
      isDefault: true,
      sortOrder: 1,
      createdAt: '2025-10-30T12:07:00.000Z',
    },
    {
      id: 'cfg-opt-lx26-tow-wake',
      componentId: 'cfg-comp-lx26-tow',
      code: 'TOW-WAKE',
      partNumber: 'LX26-TOW-WAKE',
      name: 'Wake Tower & Surf Tabs',
      description: 'Powder coated tower, integrated ballast, and surf tab controls.',
      isActive: true,
      isDefault: false,
      sortOrder: 2,
      createdAt: '2025-10-30T12:07:00.000Z',
    },
    {
      id: 'cfg-opt-lx26-lux-seating-diamond',
      componentId: 'cfg-comp-lx26-lux-seating',
      code: 'SEAT-DIAMOND',
      partNumber: 'LX26-SEAT-DIA',
      name: 'Diamond Stitch',
      description: 'Diamond stitched cool-touch vinyl.',
      isActive: true,
      isDefault: true,
      sortOrder: 1,
      createdAt: '2025-10-30T12:07:00.000Z',
    },
    {
      id: 'cfg-opt-lx26-lux-seating-carbon',
      componentId: 'cfg-comp-lx26-lux-seating',
      code: 'SEAT-CARBON',
      partNumber: 'LX26-SEAT-CAR',
      name: 'Carbon Weave',
      description: 'Carbon weave with contrast piping.',
      isActive: true,
      isDefault: false,
      sortOrder: 2,
      createdAt: '2025-10-30T12:07:00.000Z',
    },
    {
      id: 'cfg-opt-lx26-lux-lighting-rgb',
      componentId: 'cfg-comp-lx26-lux-lighting',
      code: 'LGT-RGB',
      partNumber: 'LX26-LGT-RGB',
      name: 'RGB Lighting',
      description: 'Full RGB interior and underwater lighting kit.',
      isActive: true,
      isDefault: true,
      sortOrder: 1,
      createdAt: '2025-10-30T12:07:00.000Z',
    },
    {
      id: 'cfg-opt-lx26-lux-lighting-white',
      componentId: 'cfg-comp-lx26-lux-lighting',
      code: 'LGT-WHITE',
      partNumber: 'LX26-LGT-WHT',
      name: 'Signature White',
      description: 'Warm white ambient lighting package.',
      isActive: true,
      isDefault: false,
      sortOrder: 2,
      createdAt: '2025-10-30T12:07:00.000Z',
    },
    {
      id: 'cfg-opt-lx24-engine-300',
      componentId: 'cfg-comp-lx24-engine',
      code: 'ENG-300',
      partNumber: 'LX24-ENG-300',
      name: '300 HP V8',
      description: 'Standard 300 HP outboard.',
      isActive: true,
      isDefault: true,
      sortOrder: 1,
      createdAt: '2025-10-30T12:07:00.000Z',
    },
    {
      id: 'cfg-opt-lx24-engine-350',
      componentId: 'cfg-comp-lx24-engine',
      code: 'ENG-350',
      partNumber: 'LX24-ENG-350',
      name: '350 HP V10',
      description: 'High output engine for sport trims.',
      isActive: true,
      isDefault: false,
      sortOrder: 2,
      createdAt: '2025-10-30T12:07:00.000Z',
    },
    {
      id: 'cfg-opt-lx24-helm-dual',
      componentId: 'cfg-comp-lx24-helm',
      code: 'HELM-DUAL',
      partNumber: 'LX24-HELM-DUAL',
      name: 'Dual Display Helm',
      description: 'Dual 12" displays with glass cockpit controls.',
      isActive: true,
      isDefault: true,
      sortOrder: 1,
      createdAt: '2025-10-30T12:07:00.000Z',
    },
    {
      id: 'cfg-opt-lx24-helm-analog',
      componentId: 'cfg-comp-lx24-helm',
      code: 'HELM-ANALOG',
      partNumber: 'LX24-HELM-ANA',
      name: 'Analog Gauge Helm',
      description: 'Analog instrumentation with 7" MFD.',
      isActive: true,
      isDefault: false,
      sortOrder: 2,
      createdAt: '2025-10-30T12:07:00.000Z',
    },
    {
      id: 'cfg-opt-lx24-speaker-standard',
      componentId: 'cfg-comp-lx24-speakers',
      code: 'SPK-STD',
      partNumber: 'LX24-SPK-STD',
      name: 'Standard 6 Speaker',
      description: 'Standard six-speaker cabin audio.',
      isActive: true,
      isDefault: true,
      sortOrder: 1,
      createdAt: '2025-10-30T12:07:00.000Z',
    },
    {
      id: 'cfg-opt-lx24-speaker-premium',
      componentId: 'cfg-comp-lx24-speakers',
      code: 'SPK-PREM',
      partNumber: 'LX24-SPK-PREM',
      name: 'Premium 10 Speaker',
      description: 'Upgraded cabin plus tower speakers.',
      isActive: true,
      isDefault: false,
      sortOrder: 2,
      createdAt: '2025-10-30T12:07:00.000Z',
    },
    {
      id: 'cfg-opt-lx24-subwoofer-none',
      componentId: 'cfg-comp-lx24-subwoofer',
      code: 'SUB-NONE',
      partNumber: 'LX24-SUB-NONE',
      name: 'No Subwoofer',
      description: 'Skip subwoofer installation.',
      isActive: true,
      isDefault: true,
      sortOrder: 1,
      createdAt: '2025-10-30T12:07:00.000Z',
    },
    {
      id: 'cfg-opt-lx24-subwoofer-premium',
      componentId: 'cfg-comp-lx24-subwoofer',
      code: 'SUB-PREM',
      partNumber: 'LX24-SUB-PREM',
      name: '12" Subwoofer',
      description: '12" subwoofer with amp.',
      isActive: true,
      isDefault: false,
      sortOrder: 2,
      createdAt: '2025-10-30T12:07:00.000Z',
    },
    {
      id: 'cfg-opt-lx22-fuel-50gal',
      componentId: 'cfg-comp-lx22-fuel',
      code: 'FUEL-50',
      partNumber: 'LX22-FUEL-50',
      name: '50 Gallon Tank',
      description: 'Standard 50 gallon fuel capacity.',
      isActive: true,
      isDefault: true,
      sortOrder: 1,
      createdAt: '2025-10-30T12:07:00.000Z',
    },
    {
      id: 'cfg-opt-lx22-fuel-65gal',
      componentId: 'cfg-comp-lx22-fuel',
      code: 'FUEL-65',
      partNumber: 'LX22-FUEL-65',
      name: '65 Gallon Tank',
      description: 'Expanded fuel tank for extended range.',
      isActive: true,
      isDefault: false,
      sortOrder: 2,
      createdAt: '2025-10-30T12:07:00.000Z',
    },
    {
      id: 'cfg-opt-lx22-bimini-sun',
      componentId: 'cfg-comp-lx22-bimini',
      code: 'BIM-SUN',
      partNumber: 'LX22-BIM-SUN',
      name: 'Sunshade Bimini',
      description: 'Sunshade bimini top with quick deploy hardware.',
      isActive: true,
      isDefault: true,
      sortOrder: 1,
      createdAt: '2025-10-30T12:07:00.000Z',
    },
    {
      id: 'cfg-opt-lx22-bimini-extended',
      componentId: 'cfg-comp-lx22-bimini',
      code: 'BIM-EXT',
      partNumber: 'LX22-BIM-EXT',
      name: 'Extended Shade',
      description: 'Extended coverage bimini with sun wings.',
      isActive: true,
      isDefault: false,
      sortOrder: 2,
      createdAt: '2025-10-30T12:07:00.000Z',
    },
    {
      id: 'cfg-opt-lx22-lux-seating-perf',
      componentId: 'cfg-comp-lx22-lux-seating',
      code: 'SEAT-PERF',
      partNumber: 'LX22-SEAT-PERF',
      name: 'Perforated Cool-Touch',
      description: 'Perforated cool-touch upholstery.',
      isActive: true,
      isDefault: true,
      sortOrder: 1,
      createdAt: '2025-10-30T12:07:00.000Z',
    },
    {
      id: 'cfg-opt-lx22-lux-seating-contrast',
      componentId: 'cfg-comp-lx22-lux-seating',
      code: 'SEAT-CONTRAST',
      partNumber: 'LX22-SEAT-CON',
      name: 'Contrast Piping',
      description: 'Contrast piping with memory foam inserts.',
      isActive: true,
      isDefault: false,
      sortOrder: 2,
      createdAt: '2025-10-30T12:07:00.000Z',
    },
    {
      id: 'cfg-opt-lx22-lux-galley-deluxe',
      componentId: 'cfg-comp-lx22-lux-galley',
      code: 'GAL-DELUXE',
      partNumber: 'LX22-GAL-DEL',
      name: 'Deluxe Galley',
      description: 'Solid-surface galley with fridge and sink.',
      isActive: true,
      isDefault: true,
      sortOrder: 1,
      createdAt: '2025-10-30T12:07:00.000Z',
    },
    {
      id: 'cfg-opt-lx22-lux-galley-entertain',
      componentId: 'cfg-comp-lx22-lux-galley',
      code: 'GAL-ENT',
      partNumber: 'LX22-GAL-ENT',
      name: 'Entertainer Galley',
      description: 'Wine chiller, ice maker, and prep surface.',
      isActive: true,
      isDefault: false,
      sortOrder: 2,
      createdAt: '2025-10-30T12:07:00.000Z',
    },
    {
      id: 'cfg-opt-lx21-livewell-dual',
      componentId: 'cfg-comp-lx21-livewell',
      code: 'LIVE-DUAL',
      partNumber: 'LX21-LIVE-DUAL',
      name: 'Dual 20G Livewell',
      description: 'Dual 20 gallon recirculating livewell system.',
      isActive: true,
      isDefault: true,
      sortOrder: 1,
      createdAt: '2025-10-30T12:07:00.000Z',
    },
    {
      id: 'cfg-opt-lx21-livewell-pro',
      componentId: 'cfg-comp-lx21-livewell',
      code: 'LIVE-PRO',
      partNumber: 'LX21-LIVE-PRO',
      name: 'Pro Aerated Livewell',
      description: 'Dual livewell with oxygenation system.',
      isActive: true,
      isDefault: false,
      sortOrder: 2,
      createdAt: '2025-10-30T12:07:00.000Z',
    },
    {
      id: 'cfg-opt-lx21-rod-locker',
      componentId: 'cfg-comp-lx21-rod',
      code: 'ROD-LOCKER',
      partNumber: 'LX21-ROD-LOCK',
      name: 'Locking Rod Locker',
      description: 'Locking bow rod locker with LED lighting.',
      isActive: true,
      isDefault: true,
      sortOrder: 1,
      createdAt: '2025-10-30T12:07:00.000Z',
    },
    {
      id: 'cfg-opt-lx21-rod-deck',
      componentId: 'cfg-comp-lx21-rod',
      code: 'ROD-DECK',
      partNumber: 'LX21-ROD-DECK',
      name: 'Deck Tube Storage',
      description: 'Deck tube storage with quick access mounts.',
      isActive: true,
      isDefault: false,
      sortOrder: 2,
      createdAt: '2025-10-30T12:07:00.000Z',
    },
    {
      id: 'cfg-opt-lx21-electronics-hds',
      componentId: 'cfg-comp-lx21-electronics',
      code: 'ELEC-HDS',
      partNumber: 'LX21-ELEC-HDS',
      name: 'Lowrance HDS Package',
      description: 'Dual HDS 12" displays with networking.',
      isActive: true,
      isDefault: true,
      sortOrder: 1,
      createdAt: '2025-10-30T12:07:00.000Z',
    },
    {
      id: 'cfg-opt-lx21-electronics-solix',
      componentId: 'cfg-comp-lx21-electronics',
      code: 'ELEC-SOLIX',
      partNumber: 'LX21-ELEC-SOL',
      name: 'Humminbird Solix',
      description: 'Dual Solix 15" displays with Mega Imaging.',
      isActive: true,
      isDefault: false,
      sortOrder: 2,
      createdAt: '2025-10-30T12:07:00.000Z',
    },
    {
      id: 'cfg-opt-lx21-trolling-112',
      componentId: 'cfg-comp-lx21-trolling',
      code: 'TROLL-112',
      partNumber: 'LX21-TROLL-112',
      name: '112lb Ultrex',
      description: 'Minn Kota Ultrex 112 with i-Pilot Link.',
      isActive: true,
      isDefault: true,
      sortOrder: 1,
      createdAt: '2025-10-30T12:07:00.000Z',
    },
    {
      id: 'cfg-opt-lx21-trolling-ghost',
      componentId: 'cfg-comp-lx21-trolling',
      code: 'TROLL-GHOST',
      partNumber: 'LX21-TROLL-GHO',
      name: 'Lowrance Ghost',
      description: 'Lowrance Ghost brushless trolling motor.',
      isActive: true,
      isDefault: false,
      sortOrder: 2,
      createdAt: '2025-10-30T12:07:00.000Z',
    },
  ],
  productConfigurationDependencies: [
    {
      id: 'cfg-dep-lx26-battery-heavy-charger',
      optionId: 'cfg-opt-lx26-battery-heavy',
      dependsOnOptionId: 'cfg-opt-lx26-charger-50a',
      dependencyType: 'REQUIRES',
      createdAt: '2025-10-30T12:08:00.000Z',
    },
    {
      id: 'cfg-dep-lx26-stereo-lighting',
      optionId: 'cfg-opt-lx26-stereo-concert',
      dependsOnOptionId: 'cfg-opt-lx26-lux-lighting-rgb',
      dependencyType: 'REQUIRES',
      createdAt: '2025-10-30T12:08:00.000Z',
    },
    {
      id: 'cfg-dep-lx24-subwoofer-premium',
      optionId: 'cfg-opt-lx24-subwoofer-premium',
      dependsOnOptionId: 'cfg-opt-lx24-speaker-premium',
      dependencyType: 'REQUIRES',
      createdAt: '2025-10-30T12:08:00.000Z',
    },
    {
      id: 'cfg-dep-lx22-galley-entertain',
      optionId: 'cfg-opt-lx22-lux-galley-entertain',
      dependsOnOptionId: 'cfg-opt-lx22-lux-seating-perf',
      dependencyType: 'REQUIRES',
      createdAt: '2025-10-30T12:08:00.000Z',
    },
    {
      id: 'cfg-dep-lx21-electronics-ghost',
      optionId: 'cfg-opt-lx21-electronics-solix',
      dependsOnOptionId: 'cfg-opt-lx21-trolling-ghost',
      dependencyType: 'REQUIRES',
      createdAt: '2025-10-30T12:08:00.000Z',
    },
  ],
  equipment: [
    {
      id: 'cmeq001',
      name: 'Rivet Gun',
      description: 'Pneumatic rivet gun for hull assembly',
      isActive: true,
      createdAt: '2025-09-23T16:12:09.145Z',
    },
    {
      id: 'cmeq002',
      name: 'Spray Booth',
      description: 'Paint and coating spray booth',
      isActive: true,
      createdAt: '2025-09-23T16:12:09.145Z',
    },
    {
      id: 'cmeq003',
      name: 'Engine Hoist',
      description: '2-ton engine hoist for installation',
      isActive: true,
      createdAt: '2025-09-23T16:12:09.145Z',
    },
    {
      id: 'cmeq004',
      name: 'Lamination Table',
      description: 'Large work table for lamination',
      isActive: true,
      createdAt: '2025-09-23T16:12:09.145Z',
    },
    {
      id: 'cmeq005',
      name: 'Pressure Washer',
      description: 'Industrial pressure washer',
      isActive: true,
      createdAt: '2025-09-23T16:12:09.145Z',
    },
    {
      id: 'cmeq006',
      name: 'Leak Detector',
      description: 'Electronic leak detection system',
      isActive: true,
      createdAt: '2025-09-23T16:12:09.145Z',
    },
  ],
  stationEquipment: [
    {
      id: 'cmsteq001',
      stationId: 'cmfwr6rcp0018mv56qark6z6q',
      equipmentId: 'cmeq001',
      createdAt: '2025-09-23T16:12:09.145Z',
    },
    {
      id: 'cmsteq002',
      stationId: 'cmfwr6rco0011mv56n62uc0sj',
      equipmentId: 'cmeq004',
      createdAt: '2025-09-23T16:12:09.145Z',
    },
    {
      id: 'cmsteq003',
      stationId: 'cmfwr6rcp001emv569rfhss65',
      equipmentId: 'cmeq003',
      createdAt: '2025-09-23T16:12:09.145Z',
    },
    {
      id: 'cmsteq004',
      stationId: 'cmfwr6rcp001cmv56ybyjly1h',
      equipmentId: 'cmeq005',
      createdAt: '2025-09-23T16:12:09.145Z',
    },
    {
      id: 'cmsteq005',
      stationId: 'cmfwr6rcp0016mv56la2yxlr6',
      equipmentId: 'cmeq006',
      createdAt: '2025-09-23T16:12:09.145Z',
    },
    {
      id: 'cmsteq006',
      stationId: 'cmfwr6rco000ymv56m8bynk1b',
      equipmentId: 'cmeq002',
      createdAt: '2025-09-23T16:12:09.145Z',
    },
  ],
  stationMembers: [
    {
      id: 'cmstmem001',
      stationId: 'cmfwr6rcp0018mv56qark6z6q',
      userId: 'cmfwr6s9e001lmv567pcikcpy',
      isActive: true,
      createdAt: '2025-09-23T16:12:09.145Z',
    },
    {
      id: 'cmstmem002',
      stationId: 'cmfwr6rez001gmv56h7f2kn9n',
      userId: 'cmfwr6s9e001lmv567pcikcpy',
      isActive: true,
      createdAt: '2025-09-23T16:12:09.145Z',
    },
    {
      id: 'cmstmem003',
      stationId: 'cmfwr6rco0011mv56n62uc0sj',
      userId: 'cmfwr6s9e001mmv56newuser01',
      isActive: true,
      createdAt: '2025-09-23T16:12:09.145Z',
    },
    {
      id: 'cmstmem004',
      stationId: 'cmfwr6rco000ymv56m8bynk1b',
      userId: 'cmfwr6s9e001nmv56newuser02',
      isActive: true,
      createdAt: '2025-09-23T16:12:09.145Z',
    },
    {
      id: 'cmstmem005',
      stationId: 'cmfwr6rcp0018mv56qark6z6q',
      userId: 'cmfwr6s9e001kmv5660mr74fo',
      isActive: true,
      createdAt: '2025-09-23T16:12:09.145Z',
    },
  ],
  payRateHistory: [
    {
      id: 'cmprh001',
      userId: 'cmfwr6s9e001lmv567pcikcpy',
      oldRate: null,
      newRate: 22.5,
      changedBy: 'cmfwr6s9e001jmv5659vvhrqm',
      reason: 'Initial rate',
      createdAt: '2025-09-23T16:12:09.145Z',
    },
    {
      id: 'cmprh002',
      userId: 'cmfwr6s9e001kmv5660mr74fo',
      oldRate: null,
      newRate: 35.0,
      changedBy: 'cmfwr6s9e001jmv5659vvhrqm',
      reason: 'Initial rate',
      createdAt: '2025-09-23T16:12:09.145Z',
    },
    {
      id: 'cmprh003',
      userId: 'cmfwr6s9e001jmv5659vvhrqm',
      oldRate: null,
      newRate: 45.0,
      changedBy: 'cmfwr6s9e001jmv5659vvhrqm',
      reason: 'Initial rate',
      createdAt: '2025-09-23T16:12:09.145Z',
    },
    {
      id: 'cmprh004',
      userId: 'cmfwr6s9e001mmv56newuser01',
      oldRate: null,
      newRate: 20.0,
      changedBy: 'cmfwr6s9e001jmv5659vvhrqm',
      reason: 'Initial rate',
      createdAt: '2025-09-23T16:12:09.145Z',
    },
    {
      id: 'cmprh005',
      userId: 'cmfwr6s9e001nmv56newuser02',
      oldRate: null,
      newRate: 25.0,
      changedBy: 'cmfwr6s9e001jmv5659vvhrqm',
      reason: 'Initial rate',
      createdAt: '2025-09-23T16:12:09.145Z',
    },
  ],
  stationMetrics: [],
  workOrderNotes: [],
  workOrderAttachments: [],
  workOrderVersions: [],
  workInstructionVersions: [],
}
